global using System.Linq.Expressions;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using ChatService.Contract.Settings;
global using Microsoft.Extensions.Options;
global using MongoDB.Driver;
global using ChatService.Domain.Abstractions.Repositories;
global using ChatService.Domain.Models;
global using ChatService.Domain.Abstractions;
