global using MediatR;
global using ChatService.Contract.Abstractions.Shared;
global using ChatService.Contract.Helpers;
global using ChatService.Contract.EventBus.Abstractions.Message;
global using ChatService.Contract.Abstractions.Message;
global using Microsoft.AspNetCore.Http;
global using System.Text.Json.Serialization;
global using MongoDB.Bson;
global using FluentValidation;
